export const routes = {
  home: '/',
  auth: {
    register: '/register',
    login: '/login',
  },
  dashboard: {
    root: '/dashboard',
    overview: '/dashboard/overview',
    staff: '/dashboard/staff',
    panel: '/dashboard/panel',
    newPanel: '/dashboard/panel/new',
    patients: '/dashboard/patients',
    newPatient: '/dashboard/patients/new',
    patientProfile: '/dashboard/patient-profile',
    patientCare: '/dashboard/patient-care',
    report: '/dashboard/report',
    billing: '/dashboard/billing',
    dutyRoster: '/dashboard/duty-roster',
    inSession: '/dashboard/in-session',
    medication: '/dashboard/medication',
    patientSchedule: '/dashboard/patient-schedule',
    schedule: '/dashboard/schedule',
    inventory: '/dashboard/inventory',
    itemList: '/dashboard/item-list',
    stock: '/dashboard/stock',
    stockReport: '/dashboard/stock-report',
    suppliers: '/dashboard/suppliers',
    orders: '/dashboard/orders',
    settings: '/dashboard/settings',
  },
} as const;